import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:cloud_firestore/cloud_firestore.dart';

import '../../../core/classic_theme.dart';
import '../../../core/design_tokens.dart';
import '../../../core/entitlements.dart';
import '../../../core/responsive.dart';
import '../../../core/saas_models.dart';
import '../../../providers/dashboard_layout_provider.dart';
import '../../../utils/ui_feedback.dart';

/// What each tenant is allowed to do.
///
/// The one place a switch is flipped. It must be impossible to save a
/// configuration the app will refuse to run, so:
///
///  * Toggles are generated from [FeatureCatalog], grouped by tier. Basic tiers
///    have no switch; only add-ons do.
///  * Storage mode is a separate control. Choosing an offline mode hides the
///    online tiers entirely and pins devices and outlets to one.
///  * Turning a feature off turns its dependants off, and the rows say why.
///    Turning a feature on whose parent is off is not possible; the row says
///    what to switch on first.
///  * A storage-mode change is **requested**, not applied. The tenant's owner
///    completes it on their own device; until then the store keeps running on
///    its current mode. See FEATURE_MASTER_PLAN.md §9.
///  * A preview strip shows exactly which dashboard cards the owner will see,
///    generated by the same resolver the app uses.
class AdminFeaturesView extends ConsumerStatefulWidget {
  const AdminFeaturesView({super.key});

  @override
  ConsumerState<AdminFeaturesView> createState() => _AdminFeaturesViewState();
}

class _AdminFeaturesViewState extends ConsumerState<AdminFeaturesView> {
  String? _selectedOrgId;
  String _selectedOrgName = '';
  bool _isLoadingOrg = false;
  bool _isSaving = false;
  bool _dirty = false;

  Map<String, bool> _features = {};
  int _maxDevices = 1;
  int _maxOutlets = 1;
  String _profileId = PlanProfile.connected.id;

  /// The mode the store is running on right now.
  String _liveStorageMode = StorageModes.cloudSync;

  /// The mode being configured. Differs from live only while a change is
  /// requested but not yet completed by the owner.
  String _targetStorageMode = StorageModes.cloudSync;

  /// `organizations/{orgId}.pendingStorageChange`, if any.
  Map<String, dynamic>? _pending;

  bool get _targetIsOffline => StorageModes.isOffline(_targetStorageMode);
  bool get _modeChangeRequested => _targetStorageMode != _liveStorageMode;

  // ───────────────────────────────────────────────────────────── data

  Future<void> _loadTenant(String orgId, String orgName) async {
    setState(() {
      _selectedOrgId = orgId;
      _selectedOrgName = orgName;
      _isLoadingOrg = true;
      _dirty = false;
    });

    try {
      final fs = FirebaseFirestore.instance;
      final licDoc = await fs.collection('licenses').doc(orgId).get();
      final orgDoc = await fs.collection('organizations').doc(orgId).get();
      final lic = licDoc.data();
      final org = orgDoc.data();

      // Legacy mirror, read only while documents predating this console exist.
      Map<String, dynamic>? legacy;
      if (lic == null || lic['features'] == null) {
        final featDoc = await fs.collection('features').doc(orgId).get();
        legacy = featDoc.data();
      }

      final profileId =
          (lic?['planProfile'] ?? legacy?['planProfile'])?.toString();
      final profile = profileId != null
          ? PlanProfile.byId(profileId)
          : PlanProfile.forTier(lic?['planTier']?.toString());

      final resolved = <String, bool>{}..addAll(profile.features);
      final raw = lic?['features'] ?? legacy?['features'];
      if (raw is Map) {
        for (final e in raw.entries) {
          resolved[e.key.toString()] = e.value == true;
        }
      }

      final live = (org?['storageMode'] ?? profile.storageMode).toString();
      final pending = org?['pendingStorageChange'];

      _features = resolved;
      _profileId = profile.id;
      _maxDevices = _readInt(lic?['maxDevices'], profile.maxDevices);
      _maxOutlets = _readInt(lic?['maxFranchises'], profile.maxOutlets);
      _liveStorageMode = live.toUpperCase();
      _pending = pending is Map ? Map<String, dynamic>.from(pending) : null;
      _targetStorageMode = (_pending != null && _pending!['status'] == 'PENDING')
          ? (_pending!['to'] ?? live).toString().toUpperCase()
          : _liveStorageMode;
      _applyHardConstraints();
    } catch (e) {
      if (mounted) AppToast.showError(context, 'Could not read this store: $e');
    } finally {
      if (mounted) setState(() => _isLoadingOrg = false);
    }
  }

  static int _readInt(dynamic v, int fallback) {
    if (v is num && v > 0) return v.toInt();
    return fallback;
  }

  /// Whatever the operator clicks, an offline target ends up with one device,
  /// one outlet and nothing that needs the cloud or a second screen.
  void _applyHardConstraints() {
    if (_targetIsOffline) {
      _maxDevices = 1;
      _maxOutlets = 1;
      for (final def in FeatureCatalog.all) {
        if (def.need != FeatureNeed.none || def.tier.isOnline) {
          _features[def.key] = false;
        }
      }
    } else {
      // Online basic ships with every online plan.
      for (final def in FeatureCatalog.byTier(CommercialTier.onlineBasic)) {
        _features[def.key] = true;
      }
      if (_maxDevices <= 1) {
        for (final def in FeatureCatalog.all) {
          if (def.need == FeatureNeed.secondDevice) _features[def.key] = false;
        }
      }
    }
    // Offline basic is always on, and the legacy flag mirrors the mode.
    for (final def in FeatureCatalog.byTier(CommercialTier.offlineBasic)) {
      _features[def.key] = true;
    }
    _features[FeatureKeys.pureOfflineMode] = _targetIsOffline;
    _cascadeOff();
  }

  /// A dependant can never be on while its parent is off.
  void _cascadeOff() {
    var changed = true;
    while (changed) {
      changed = false;
      for (final def in FeatureCatalog.all) {
        if (_features[def.key] != true) continue;
        for (final dep in def.dependsOn) {
          if (_features[dep] != true) {
            _features[def.key] = false;
            changed = true;
            break;
          }
        }
      }
    }
  }

  void _applyProfile(PlanProfile profile) {
    setState(() {
      _profileId = profile.id;
      _features = Map<String, bool>.from(profile.features);
      _maxDevices = profile.maxDevices;
      _maxOutlets = profile.maxOutlets;
      _targetStorageMode = profile.storageMode;
      _applyHardConstraints();
      _dirty = true;
    });
    AppToast.showSuccess(
      context,
      '${profile.label} loaded into the editor',
      subtitle: 'Nothing is live until you save.',
    );
  }

  void _setTargetMode(String mode) {
    setState(() {
      _targetStorageMode = mode;
      _applyHardConstraints();
      _dirty = true;
    });
  }

  void _toggle(String key, bool value) {
    setState(() {
      _features[key] = value;
      if (!value) {
        for (final k in FeatureCatalog.dependants(key)) {
          _features[k] = false;
        }
      }
      _dirty = true;
    });
  }

  /// The resolver's view of what is being configured, for the preview strip.
  Entitlements _preview() {
    final license = SaasLicense(
      planTier: _profileId,
      planProfile: _profileId,
      status: 'ACTIVE',
      maxFranchises: _maxOutlets,
      maxUsers: 99,
      maxDevices: _maxDevices,
      features: Map<String, bool>.from(_features),
      startDate: DateTime.now(),
      endDate: DateTime.now().add(const Duration(days: 365)),
    );
    return Entitlements.fromLicense(license, storageMode: _targetStorageMode);
  }

  Future<void> _save() async {
    final orgId = _selectedOrgId;
    if (orgId == null) return;
    setState(() => _isSaving = true);

    try {
      _applyHardConstraints();
      final fs = FirebaseFirestore.instance;
      final now = FieldValue.serverTimestamp();
      final batch = fs.batch();

      // The authority.
      batch.set(fs.collection('licenses').doc(orgId), {
        'features': _features,
        'planProfile': _profileId,
        'maxDevices': _maxDevices,
        'maxFranchises': _maxOutlets,
        'updatedAt': now,
      }, SetOptions(merge: true));

      // Legacy mirror — one more release.
      batch.set(fs.collection('features').doc(orgId), {
        'features': _features,
        'planProfile': _profileId,
        'updatedAt': now,
        'updatedBy': 'master_admin',
      }, SetOptions(merge: true));

      // A storage-mode change is requested, never applied here. The owner
      // completes provisioning and migration on their device; the mode flips
      // there, after verification. Nothing about the store's current data
      // path changes at this save.
      if (_modeChangeRequested) {
        batch.set(fs.collection('organizations').doc(orgId), {
          'pendingStorageChange': {
            'from': _liveStorageMode,
            'to': _targetStorageMode,
            'status': 'PENDING',
            'requestedBy': 'master_admin',
            'requestedAt': now,
            'steps': <String, dynamic>{},
          },
          'updatedAt': now,
        }, SetOptions(merge: true));
      }

      // The guest-facing web menu reads these two flags and nothing else about
      // the plan, so it can show "not taking orders online" the moment an
      // add-on is switched off — without redeploying the site.
      final preview = _preview();
      batch.set(fs.collection('public_stores').doc(orgId), {
        'onlineMenuEnabled': preview.isEnabled(FeatureKeys.onlineMenu),
        'onlineOrderingEnabled': preview.isEnabled(FeatureKeys.onlineOrderingEnabled),
        'qrOrderingEnabled': preview.isEnabled(FeatureKeys.qrOrdering),
        'entitlementsUpdatedAt': now,
      }, SetOptions(merge: true));

      final enabled = _features.entries
          .where((e) => e.value)
          .map((e) => e.key)
          .toList()
        ..sort();

      batch.set(fs.collection('audit_logs').doc(), {
        'action': 'FEATURES_UPDATED',
        'targetOrgId': orgId,
        'targetOrgName': _selectedOrgName,
        'details': 'Plan $_profileId · mode $_liveStorageMode'
            '${_modeChangeRequested ? ' → $_targetStorageMode (requested)' : ''}'
            ' · $_maxDevices device(s), $_maxOutlets outlet(s) · on: '
            '${enabled.join(', ')}',
        'by': 'master_admin',
        'timestamp': now,
      });

      await batch.commit();

      if (mounted) {
        setState(() {
          _dirty = false;
          if (_modeChangeRequested) {
            _pending = {
              'from': _liveStorageMode,
              'to': _targetStorageMode,
              'status': 'PENDING',
            };
          }
        });
        AppToast.showSuccess(
          context,
          'Saved',
          subtitle: _modeChangeRequested
              ? 'The owner will be asked to complete the storage change at '
                  'their next sign-in.'
              : 'Tills pick this up on their next sync.',
        );
      }
    } catch (e) {
      if (mounted) AppToast.showError(context, 'Could not save: $e');
    } finally {
      if (mounted) setState(() => _isSaving = false);
    }
  }

  Future<void> _cancelPendingChange() async {
    final orgId = _selectedOrgId;
    if (orgId == null) return;
    try {
      await FirebaseFirestore.instance
          .collection('organizations')
          .doc(orgId)
          .set({
        'pendingStorageChange': FieldValue.delete(),
        'updatedAt': FieldValue.serverTimestamp(),
      }, SetOptions(merge: true));
      if (mounted) {
        setState(() {
          _pending = null;
          _targetStorageMode = _liveStorageMode;
          _applyHardConstraints();
          _dirty = false;
        });
        AppToast.showSuccess(context, 'Storage change cancelled',
            subtitle: 'The store stays on $_liveStorageMode.');
      }
    } catch (e) {
      if (mounted) AppToast.showError(context, 'Could not cancel: $e');
    }
  }

  // ───────────────────────────────────────────────────────────── build

  @override
  Widget build(BuildContext context) {
    return StreamBuilder<QuerySnapshot>(
      stream: FirebaseFirestore.instance.collection('organizations').snapshots(),
      builder: (context, orgSnap) {
        final List<QueryDocumentSnapshot<Object?>> orgDocs =
            orgSnap.data?.docs ?? const <QueryDocumentSnapshot<Object?>>[];

        if (_selectedOrgId == null && orgDocs.isNotEmpty) {
          final first = orgDocs.first;
          final firstData = first.data() as Map<String, dynamic>;
          WidgetsBinding.instance.addPostFrameCallback((_) {
            if (mounted && _selectedOrgId == null) {
              _loadTenant(first.id, (firstData['name'] ?? first.id).toString());
            }
          });
        }

        final compact = context.isCompactScreen;
        final gutter = context.pageGutter;

        return Column(
          children: [
            Expanded(
              child: ListView(
                padding: EdgeInsets.fromLTRB(gutter, gutter, gutter, DS.space10),
                children: [
                  _header(orgDocs, compact),
                  const SizedBox(height: DS.space5),
                  if (_selectedOrgId == null)
                    _emptyState()
                  else if (_isLoadingOrg)
                    const Padding(
                      padding: EdgeInsets.symmetric(vertical: DS.space10),
                      child: Center(child: CircularProgressIndicator()),
                    )
                  else ...[
                    if (_pending != null && _pending!['status'] != 'DONE')
                      _pendingBanner(),
                    _profileSection(),
                    const SizedBox(height: DS.space5),
                    _storageSection(),
                    const SizedBox(height: DS.space5),
                    _limitsSection(),
                    const SizedBox(height: DS.space5),
                    ..._featureSections(),
                    _previewSection(),
                  ],
                ],
              ),
            ),
            if (_selectedOrgId != null && !_isLoadingOrg) _saveBar(),
          ],
        );
      },
    );
  }

  Widget _card({required Widget child}) => Container(
        padding: const EdgeInsets.all(DS.space4),
        decoration: ClassicTheme.cardDecorationFor(context),
        child: child,
      );

  Widget _header(List<QueryDocumentSnapshot<Object?>> orgDocs, bool compact) {
    final picker = Container(
      padding: const EdgeInsets.symmetric(horizontal: DS.space3),
      decoration: BoxDecoration(
        color: context.inputFill,
        borderRadius: BorderRadius.circular(DS.radiusMd),
        border: Border.all(color: context.borderColor),
      ),
      child: DropdownButtonHideUnderline(
        child: DropdownButton<String>(
          value: _selectedOrgId,
          isExpanded: true,
          dropdownColor: context.surfaceColor,
          borderRadius: BorderRadius.circular(DS.radiusMd),
          hint: Text('Choose a store',
              style:
                  TextStyle(color: context.textSecondary, fontSize: DS.fontBody)),
          items: orgDocs.map<DropdownMenuItem<String>>((doc) {
            final d = doc.data() as Map<String, dynamic>;
            final name = (d['name'] ?? doc.id).toString();
            return DropdownMenuItem<String>(
              value: doc.id,
              child: Text(
                name,
                style: TextStyle(
                  fontSize: DS.fontBody,
                  fontWeight: FontWeight.w600,
                  color: context.textPrimary,
                ),
                overflow: TextOverflow.ellipsis,
              ),
            );
          }).toList(),
          onChanged: (newId) {
            if (newId == null) return;
            final doc = orgDocs.firstWhere((d) => d.id == newId);
            final d = doc.data() as Map<String, dynamic>;
            _loadTenant(newId, (d['name'] ?? newId).toString());
          },
        ),
      ),
    );

    final heading = Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          'What each store can do',
          style: TextStyle(
            fontSize: compact ? DS.fontTitle : DS.fontHeadline,
            fontWeight: FontWeight.w800,
            color: context.textPrimary,
          ),
        ),
        const SizedBox(height: DS.space1),
        Text(
          'Pick a plan to start from, then adjust. Staff only ever see the '
          'buttons for what is switched on here.',
          style: TextStyle(
            fontSize: DS.fontCaption,
            color: context.textSecondary,
            height: 1.45,
          ),
        ),
      ],
    );

    return _card(
      child: compact
          ? Column(
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: [heading, const SizedBox(height: DS.space4), picker],
            )
          : Row(
              children: [
                Expanded(child: heading),
                const SizedBox(width: DS.space5),
                SizedBox(width: 280, child: picker),
              ],
            ),
    );
  }

  Widget _emptyState() => _card(
        child: Column(
          children: [
            Icon(Icons.storefront_outlined, size: 40, color: context.textMuted),
            const SizedBox(height: DS.space3),
            Text('No store selected yet',
                style: TextStyle(
                    fontSize: DS.fontBodyLg,
                    fontWeight: FontWeight.w700,
                    color: context.textPrimary)),
            const SizedBox(height: DS.space1),
            Text('Choose one above to see and change what it can do.',
                textAlign: TextAlign.center,
                style: TextStyle(
                    fontSize: DS.fontCaption, color: context.textSecondary)),
          ],
        ),
      );

  Widget _pendingBanner() {
    final p = _pending!;
    final steps = (p['steps'] is Map) ? Map<String, dynamic>.from(p['steps']) : {};
    // Each step is written by StorageMigrationService as
    // {status: DONE|SKIPPED|FAILED, at, detail}; a skipped step counts as done
    // (an offline target needs no consent or sheet).
    bool finished(dynamic v) {
      if (v == true || v == 'done') return true;
      if (v is Map) {
        final st = v['status']?.toString().toUpperCase();
        return st == 'DONE' || st == 'SKIPPED';
      }
      return false;
    }
    final done = ['consent', 'provision', 'migrate', 'verify']
        .where((s) => finished(steps[s]))
        .length;
    return Container(
      margin: const EdgeInsets.only(bottom: DS.space5),
      padding: const EdgeInsets.all(DS.space4),
      decoration: BoxDecoration(
        color: ClassicTheme.tintWarning,
        borderRadius: BorderRadius.circular(DS.radiusLg),
        border: Border.all(color: context.warningColor.withValues(alpha: 0.5)),
      ),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Icon(Icons.swap_horiz_rounded, color: context.warningColor, size: 20),
          const SizedBox(width: DS.space3),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  'Storage change in progress: ${p['from']} → ${p['to']}',
                  style: TextStyle(
                      fontSize: DS.fontBody,
                      fontWeight: FontWeight.w700,
                      color: context.textPrimary),
                ),
                const SizedBox(height: 2),
                Text(
                  'The owner completes this on their device — $done of 4 steps '
                  'done. The store keeps running on ${p['from']} until the '
                  'last step verifies.',
                  style: TextStyle(
                      fontSize: DS.fontMicro,
                      color: context.textSecondary,
                      height: 1.4),
                ),
              ],
            ),
          ),
          const SizedBox(width: DS.space2),
          TextButton(
            onPressed: _cancelPendingChange,
            child: const Text('Cancel change'),
          ),
        ],
      ),
    );
  }

  Widget _profileSection() => _card(
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text('START FROM A PLAN', style: ClassicTheme.sectionLabel(context)),
            const SizedBox(height: DS.space3),
            LayoutBuilder(
              builder: (context, c) {
                final columns =
                    c.maxWidth < 560 ? 1 : (c.maxWidth < 900 ? 2 : 4);
                return GridView.count(
                  crossAxisCount: columns,
                  shrinkWrap: true,
                  physics: const NeverScrollableScrollPhysics(),
                  mainAxisSpacing: DS.space3,
                  crossAxisSpacing: DS.space3,
                  childAspectRatio: columns == 1 ? 4.2 : 1.35,
                  children: PlanProfile.all
                      .map((p) => _profileCard(p, columns == 1))
                      .toList(),
                );
              },
            ),
          ],
        ),
      );

  Widget _profileCard(PlanProfile profile, bool dense) {
    final selected = _profileId == profile.id;
    final accent = profile.isOffline
        ? ClassicTheme.secondaryAccent
        : ClassicTheme.primaryAccent;

    return InkWell(
      onTap: () => _applyProfile(profile),
      borderRadius: BorderRadius.circular(DS.radiusMd),
      child: Container(
        padding: const EdgeInsets.all(DS.space3),
        decoration: BoxDecoration(
          color:
              selected ? accent.withValues(alpha: 0.12) : context.sunkenSurface,
          borderRadius: BorderRadius.circular(DS.radiusMd),
          border: Border.all(
              color: selected ? accent : context.borderColor,
              width: selected ? 2 : 1),
        ),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          mainAxisSize: MainAxisSize.min,
          children: [
            Row(
              children: [
                Icon(
                  profile.isOffline
                      ? Icons.wifi_off_rounded
                      : Icons.cloud_done_rounded,
                  size: 18,
                  color: accent,
                ),
                const SizedBox(width: DS.space2),
                Expanded(
                  child: Text(profile.label,
                      style: TextStyle(
                          fontSize: DS.fontBody,
                          fontWeight: FontWeight.w700,
                          color: context.textPrimary),
                      overflow: TextOverflow.ellipsis),
                ),
                if (selected)
                  Icon(Icons.check_circle_rounded, size: 18, color: accent),
              ],
            ),
            const SizedBox(height: DS.space2),
            Flexible(
              child: Text(
                profile.description,
                style: TextStyle(
                    fontSize: DS.fontMicro,
                    color: context.textSecondary,
                    height: 1.4),
                maxLines: dense ? 2 : 4,
                overflow: TextOverflow.ellipsis,
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _storageSection() {
    final options = <String, (String, String, IconData)>{
      StorageModes.pureOffline: (
        'Offline, this device only',
        'No internet needed. Nothing leaves the till.',
        Icons.wifi_off_rounded
      ),
      StorageModes.cloudSync: (
        'Cloud ledger',
        'Orders and payments sync to the platform\'s cloud sheet.',
        Icons.cloud_done_rounded
      ),
      StorageModes.clientsOwnSheets: (
        'Client\'s own Google Sheet',
        'The store\'s own Drive holds the ledger. Owner grants access.',
        Icons.table_view_rounded
      ),
    };

    return _card(
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text('WHERE THE DATA LIVES', style: ClassicTheme.sectionLabel(context)),
          const SizedBox(height: DS.space2),
          Text(
            _modeChangeRequested
                ? 'Live: $_liveStorageMode. Saving will ask the owner to move '
                    'the store to $_targetStorageMode — provisioning, consent '
                    'and migration happen on their device, and the switch '
                    'happens only after the data is verified.'
                : 'Changing this does not move any data by itself. The owner '
                    'is asked to complete the change at their next sign-in, '
                    'and the store keeps running on the current mode until '
                    'then.',
            style: TextStyle(
                fontSize: DS.fontMicro,
                color: _modeChangeRequested
                    ? context.warningColor
                    : context.textSecondary,
                height: 1.45),
          ),
          const SizedBox(height: DS.space3),
          ...options.entries.map((e) {
            final selected = _targetStorageMode == e.key;
            final isLive = _liveStorageMode == e.key;
            return Padding(
              padding: const EdgeInsets.only(bottom: DS.space2),
              child: InkWell(
                onTap: () => _setTargetMode(e.key),
                borderRadius: BorderRadius.circular(DS.radiusMd),
                child: Container(
                  padding: const EdgeInsets.all(DS.space3),
                  decoration: BoxDecoration(
                    color: selected
                        ? ClassicTheme.primaryAccent.withValues(alpha: 0.10)
                        : context.sunkenSurface,
                    borderRadius: BorderRadius.circular(DS.radiusMd),
                    border: Border.all(
                        color: selected
                            ? ClassicTheme.primaryAccent
                            : context.borderColor,
                        width: selected ? 2 : 1),
                  ),
                  child: Row(
                    children: [
                      Icon(e.value.$3,
                          size: 20,
                          color: selected
                              ? ClassicTheme.primaryAccent
                              : context.textSecondary),
                      const SizedBox(width: DS.space3),
                      Expanded(
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Row(
                              children: [
                                Flexible(
                                  child: Text(e.value.$1,
                                      style: TextStyle(
                                          fontSize: DS.fontBody,
                                          fontWeight: FontWeight.w600,
                                          color: context.textPrimary)),
                                ),
                                if (isLive) ...[
                                  const SizedBox(width: DS.space2),
                                  Container(
                                    padding: const EdgeInsets.symmetric(
                                        horizontal: DS.space2, vertical: 2),
                                    decoration:
                                        ClassicTheme.pill(context.successColor),
                                    child: Text('live now',
                                        style: TextStyle(
                                            fontSize: 11,
                                            fontWeight: FontWeight.w700,
                                            color: context.successColor)),
                                  ),
                                ],
                              ],
                            ),
                            const SizedBox(height: 2),
                            Text(e.value.$2,
                                style: TextStyle(
                                    fontSize: DS.fontMicro,
                                    color: context.textSecondary)),
                          ],
                        ),
                      ),
                      Radio<String>(
                        value: e.key,
                        // ignore: deprecated_member_use
                        groupValue: _targetStorageMode,
                        // ignore: deprecated_member_use
                        onChanged: (v) {
                          if (v != null) _setTargetMode(v);
                        },
                      ),
                    ],
                  ),
                ),
              ),
            );
          }),
        ],
      ),
    );
  }

  Widget _limitsSection() => _card(
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text('HOW MANY', style: ClassicTheme.sectionLabel(context)),
            const SizedBox(height: DS.space3),
            LayoutBuilder(
              builder: (context, c) {
                final stacked = c.maxWidth < 520;
                final devices = _counter(
                  label: 'Devices',
                  help: _targetIsOffline
                      ? 'Offline stores run on one device. Fixed.'
                      : 'Tills, kitchen screens and waiter tablets together. '
                          'One device switches off anything that needs a second.',
                  value: _maxDevices,
                  min: 1,
                  max: 30,
                  locked: _targetIsOffline,
                  onChanged: (v) => setState(() {
                    _maxDevices = v;
                    _applyHardConstraints();
                    _dirty = true;
                  }),
                );
                final outlets = _counter(
                  label: 'Outlets',
                  help: _targetIsOffline
                      ? 'One outlet, on this device.'
                      : 'Branches under the same owner login.',
                  value: _maxOutlets,
                  min: 1,
                  max: 50,
                  locked: _targetIsOffline ||
                      _features[FeatureKeys.multiOutlet] != true,
                  onChanged: (v) => setState(() {
                    _maxOutlets = v;
                    _dirty = true;
                  }),
                );
                return stacked
                    ? Column(children: [
                        devices,
                        const SizedBox(height: DS.space3),
                        outlets
                      ])
                    : Row(children: [
                        Expanded(child: devices),
                        const SizedBox(width: DS.space3),
                        Expanded(child: outlets),
                      ]);
              },
            ),
          ],
        ),
      );

  Widget _counter({
    required String label,
    required String help,
    required int value,
    required int min,
    required int max,
    required bool locked,
    required ValueChanged<int> onChanged,
  }) =>
      Container(
        padding: const EdgeInsets.all(DS.space3),
        decoration: BoxDecoration(
          color: context.sunkenSurface,
          borderRadius: BorderRadius.circular(DS.radiusMd),
          border: Border.all(color: context.borderColor),
        ),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                Expanded(
                  child: Text(label,
                      style: TextStyle(
                          fontSize: DS.fontBody,
                          fontWeight: FontWeight.w700,
                          color: context.textPrimary)),
                ),
                if (locked) ...[
                  Icon(Icons.lock_outline_rounded,
                      size: 16, color: context.textMuted),
                  const SizedBox(width: DS.space2),
                  Text('$value',
                      style: ClassicTheme.money(context, size: DS.fontTitle)),
                ] else ...[
                  _stepper(Icons.remove_rounded,
                      value > min ? () => onChanged(value - 1) : null),
                  SizedBox(
                    width: 44,
                    child: Text('$value',
                        textAlign: TextAlign.center,
                        style: ClassicTheme.money(context, size: DS.fontTitle)),
                  ),
                  _stepper(Icons.add_rounded,
                      value < max ? () => onChanged(value + 1) : null),
                ],
              ],
            ),
            const SizedBox(height: DS.space1),
            Text(help,
                style: TextStyle(
                    fontSize: DS.fontMicro,
                    color: context.textSecondary,
                    height: 1.4)),
          ],
        ),
      );

  Widget _stepper(IconData icon, VoidCallback? onTap) => SizedBox(
        width: DS.tapTargetMin,
        height: DS.tapTargetMin,
        child: IconButton(
          onPressed: onTap,
          icon: Icon(icon, size: 18),
          style: IconButton.styleFrom(
            backgroundColor: context.surfaceColor,
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(DS.radiusSm),
              side: BorderSide(color: context.borderColor),
            ),
          ),
        ),
      );

  List<Widget> _featureSections() {
    final sections = <Widget>[];
    for (final tier in CommercialTier.values) {
      if (_targetIsOffline && tier.isOnline) continue;
      final defs = FeatureCatalog.byTier(tier);
      if (defs.isEmpty) continue;

      sections.add(Container(
        margin: const EdgeInsets.only(bottom: DS.space4),
        padding: const EdgeInsets.all(DS.space4),
        decoration: ClassicTheme.cardDecorationFor(context),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                Expanded(
                  child: Text(tier.label.toUpperCase(),
                      style: ClassicTheme.sectionLabel(context)),
                ),
                if (!tier.isAddOn)
                  Container(
                    padding: const EdgeInsets.symmetric(
                        horizontal: DS.space2, vertical: 2),
                    decoration: ClassicTheme.pill(context.successColor),
                    child: Text('included',
                        style: TextStyle(
                            fontSize: 11,
                            fontWeight: FontWeight.w700,
                            color: context.successColor)),
                  ),
              ],
            ),
            const SizedBox(height: DS.space2),
            ...defs.map(_featureRow),
          ],
        ),
      ));
    }

    if (_targetIsOffline) {
      sections.add(Container(
        margin: const EdgeInsets.only(bottom: DS.space4),
        padding: const EdgeInsets.all(DS.space4),
        decoration: BoxDecoration(
          color: ClassicTheme.tintSecondary,
          borderRadius: BorderRadius.circular(DS.radiusLg),
          border: Border.all(
              color: ClassicTheme.secondaryAccent.withValues(alpha: 0.4)),
        ),
        child: Row(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Icon(Icons.wifi_off_rounded,
                size: 18, color: ClassicTheme.secondaryAccent),
            const SizedBox(width: DS.space3),
            Expanded(
              child: Text(
                'This store runs offline on one device, so the online tiers — '
                'cloud ledger, analytics, kitchen display, waiter ordering, QR '
                'and online ordering, outlets, stock, e-mail bills — are not '
                'offered. Choose a cloud storage mode to use them.',
                style: TextStyle(
                    fontSize: DS.fontMicro,
                    color: context.textSecondary,
                    height: 1.5),
              ),
            ),
          ],
        ),
      ));
    }
    return sections;
  }

  Widget _featureRow(FeatureDef def) {
    final on = !def.isAddOn || (_features[def.key] ?? false);
    final missingDep = def.dependsOn
        .where((d) => _features[d] != true)
        .map((d) => FeatureCatalog.find(d)?.label ?? d)
        .toList();
    final blockedByDep = def.isAddOn && !on && missingDep.isNotEmpty;
    final blockedByDevices = def.need == FeatureNeed.secondDevice &&
        _maxDevices <= 1 &&
        !_targetIsOffline;

    String note = def.description;
    Color noteColor = context.textSecondary;
    if (blockedByDevices) {
      note = 'Needs a second device — raise the device count first.';
      noteColor = context.warningColor;
    } else if (blockedByDep) {
      note = 'Needs ${missingDep.join(' and ')} switched on first.';
      noteColor = context.warningColor;
    }

    return Padding(
      padding: const EdgeInsets.symmetric(vertical: DS.space1),
      child: Row(
        children: [
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(def.label,
                    style: TextStyle(
                        fontSize: DS.fontBody,
                        fontWeight: FontWeight.w600,
                        color: context.textPrimary)),
                const SizedBox(height: 2),
                Text(note,
                    style: TextStyle(
                        fontSize: DS.fontMicro, color: noteColor, height: 1.4)),
              ],
            ),
          ),
          const SizedBox(width: DS.space3),
          if (def.isAddOn)
            Switch.adaptive(
              value: on,
              onChanged: (blockedByDep || blockedByDevices)
                  ? null
                  : (v) => _toggle(def.key, v),
            )
          else
            Icon(Icons.check_rounded, color: context.successColor, size: 20),
        ],
      ),
    );
  }

  Widget _previewSection() {
    final ent = _preview();
    final cards = kAllDashboardCards
        .where((c) => c.isAllowedFor(entitlements: ent, role: 'OWNER'))
        .toList();
    return _card(
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text('WHAT THE OWNER WILL SEE', style: ClassicTheme.sectionLabel(context)),
          const SizedBox(height: DS.space1),
          Text(
            'Home-screen cards for this configuration, from the same resolver '
            'the app uses. If it is not here, it is not on their screen.',
            style: TextStyle(
                fontSize: DS.fontMicro,
                color: context.textSecondary,
                height: 1.4),
          ),
          const SizedBox(height: DS.space3),
          Wrap(
            spacing: DS.space2,
            runSpacing: DS.space2,
            children: cards
                .map((c) => Container(
                      padding: const EdgeInsets.symmetric(
                          horizontal: DS.space3, vertical: DS.space2),
                      decoration: BoxDecoration(
                        color: context.sunkenSurface,
                        borderRadius: BorderRadius.circular(DS.radiusPill),
                        border: Border.all(color: context.borderColor),
                      ),
                      child: Row(
                        mainAxisSize: MainAxisSize.min,
                        children: [
                          Icon(c.icon, size: 16, color: c.defaultColor),
                          const SizedBox(width: DS.space2),
                          Text(c.title,
                              style: TextStyle(
                                  fontSize: DS.fontCaption,
                                  fontWeight: FontWeight.w600,
                                  color: context.textPrimary)),
                        ],
                      ),
                    ))
                .toList(),
          ),
        ],
      ),
    );
  }

  Widget _saveBar() => Container(
        padding: EdgeInsets.fromLTRB(
            context.pageGutter, DS.space3, context.pageGutter, DS.space3),
        decoration: BoxDecoration(
          color: context.surfaceColor,
          border: Border(top: BorderSide(color: context.borderColor)),
        ),
        child: SafeArea(
          top: false,
          child: Row(
            children: [
              Expanded(
                child: Text(
                  _dirty
                      ? (_modeChangeRequested
                          ? 'Unsaved — includes a storage change request'
                          : 'Unsaved changes for $_selectedOrgName')
                      : 'Everything saved for $_selectedOrgName',
                  style: TextStyle(
                      fontSize: DS.fontCaption,
                      fontWeight: FontWeight.w600,
                      color:
                          _dirty ? context.warningColor : context.textSecondary),
                  overflow: TextOverflow.ellipsis,
                ),
              ),
              const SizedBox(width: DS.space3),
              ElevatedButton.icon(
                onPressed: (_isSaving || !_dirty) ? null : _save,
                icon: _isSaving
                    ? const SizedBox(
                        width: 16,
                        height: 16,
                        child: CircularProgressIndicator(
                            strokeWidth: 2, color: Colors.white))
                    : const Icon(Icons.check_rounded, size: 18),
                label: Text(_isSaving ? 'Saving' : 'Save'),
              ),
            ],
          ),
        ),
      );
}
